-- Report Card System - Supabase (Postgres) schema.
-- Run this ONCE in Supabase -> SQL Editor. Safe to run again (it never deletes data).

create table if not exists settings(
  k text primary key,
  v text not null
);

create table if not exists users(
  id varchar(24) primary key,
  name varchar(150) not null,
  username varchar(60) not null unique,
  pass varchar(255) not null,
  role varchar(20) not null check (role in ('admin','headteacher','teacher')),
  assign text not null default '[]',
  must_change smallint not null default 1
);

create table if not exists classes(
  id varchar(40) primary key,
  name varchar(60) not null,
  teacher_id varchar(24),
  subjects text not null default '[]'
);

create table if not exists students(
  id varchar(24) primary key,
  name varchar(150) not null,
  sex varchar(1) not null default '',
  adm varchar(40) unique,
  class_id varchar(40) not null references classes(id)
);
create index if not exists students_class_idx on students(class_id);

create table if not exists scores(
  year varchar(9) not null,
  term smallint not null,
  student_id varchar(24) not null references students(id) on delete cascade,
  subject varchar(100) not null,
  class_score numeric(6,2),
  exam_score numeric(6,2),
  updated_by varchar(24),
  updated_at timestamptz not null default now(),
  primary key(year, term, student_id, subject)
);

create table if not exists info(
  year varchar(9) not null,
  term smallint not null,
  student_id varchar(24) not null references students(id) on delete cascade,
  data text not null default '{}',
  primary key(year, term, student_id)
);

create table if not exists login_attempts(
  username varchar(120) not null,
  ip varchar(64) not null,
  attempts int not null default 0,
  first_at timestamptz not null,
  last_at timestamptz not null,
  locked_until timestamptz,
  primary key(username, ip)
);

create table if not exists audit_log(
  id bigint generated by default as identity primary key,
  actor_id varchar(24),
  action varchar(80) not null,
  target varchar(180),
  details varchar(1000),
  created_at timestamptz not null default now()
);
create index if not exists audit_log_created_idx on audit_log(created_at);

create table if not exists recycle_bin(
  id varchar(40) primary key,
  entity_type varchar(40) not null,
  entity_id varchar(80) not null,
  label varchar(180) not null,
  payload text not null,
  actor_id varchar(24),
  created_at timestamptz not null default now()
);

create table if not exists password_recovery(
  id smallint primary key,
  code_hash varchar(255) not null,
  created_at timestamptz not null,
  expires_at timestamptz,
  used_at timestamptz,
  target_username varchar(120)
);

create table if not exists recovery_attempts(
  username varchar(120) not null,
  ip varchar(64) not null,
  attempts int not null default 0,
  first_at timestamptz not null,
  last_at timestamptz not null,
  locked_until timestamptz,
  primary key(username, ip)
);

create table if not exists sms_messages(
  id bigint generated by default as identity primary key,
  student_id varchar(40),
  recipient varchar(30) not null,
  student_name varchar(180),
  template varchar(50),
  message text not null,
  provider varchar(40) not null default 'arkesel',
  provider_message_id varchar(120),
  status varchar(40) not null default 'submitted',
  error_message varchar(500),
  actor_id varchar(24),
  created_at timestamptz not null default now()
);

create table if not exists email_messages(
  id bigint generated by default as identity primary key,
  student_id varchar(40),
  recipient varchar(254) not null,
  student_name varchar(180),
  template varchar(50),
  subject varchar(255) not null,
  message text not null,
  provider varchar(40) not null default 'smtp',
  status varchar(40) not null default 'sent',
  error_message varchar(500),
  actor_id varchar(24),
  created_at timestamptz not null default now()
);

-- SECURITY: Supabase exposes the "public" schema through a public REST API.
-- Turning on Row Level Security (with no policies) blocks that door completely.
-- The app talks to the database directly from the server, so it is not affected.
alter table settings enable row level security;
alter table users enable row level security;
alter table classes enable row level security;
alter table students enable row level security;
alter table scores enable row level security;
alter table info enable row level security;
alter table login_attempts enable row level security;
alter table audit_log enable row level security;
alter table recycle_bin enable row level security;
alter table password_recovery enable row level security;
alter table recovery_attempts enable row level security;
alter table sms_messages enable row level security;
alter table email_messages enable row level security;
